# Generated by Django 5.0.6 on 2024-05-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='check_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=13)),
                ('role', models.CharField(max_length=50)),
                ('device_name', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='checking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=13)),
                ('role', models.CharField(max_length=50)),
                ('device_name', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('time_in', models.DateTimeField()),
            ],
        ),
    ]
