# Generated by Django 5.0.6 on 2024-05-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_record',
            name='time_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='check_record',
            name='time_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='checking',
            name='time_in',
            field=models.DateField(),
        ),
    ]
