# Generated by Django 5.0.6 on 2024-05-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0002_alter_check_record_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_record',
            name='time_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='check_record',
            name='time_out',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checking',
            name='time_in',
            field=models.DateTimeField(),
        ),
    ]
