# Generated by Django 5.0.6 on 2024-05-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0003_alter_check_record_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_record',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
