# Generated by Django 5.0.6 on 2024-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0005_alter_checker_phone_alter_checking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_record',
            name='time_in',
            field=models.CharField(max_length=250),
        ),
    ]
